import type { Metadata } from "next";
import "./globals.css";

import { Plus_Jakarta_Sans } from "next/font/google";
import Header from "./components/Header";


import ThemeToggle from "./components/ThemeToggle";
import FloatingButtons from "./components/FloatingButtons";
import { ThemeProvider } from "./components/ThemeProvider";
import CustomCursor from "./components/custom-cursor";
import ScrollProgressCircle from "./components/ScrollProgressCircle";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Contact us-BzAnalytics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <html lang="en" suppressHydrationWarning>
        <body className={`${plusJakarta.className} antialiased`}>
          <Header />
          
         
          <ThemeToggle />
          {children}
          <CustomCursor />
          <ScrollProgressCircle />
           <FloatingButtons />
        </body>
      </html>
    </ThemeProvider>
  );
}
